### ISSUE TITLE
Generator does not generate the exact filesize when datasize is not a divisor of filesize

### ISSUE THREAD

**Issue by massahud-fixeads** [rodkranz/read_test#1]
Description: when the fileSize is not a multiple of dataSize it creates bigger files

Step to reproduce:
1. run ```go run generate.go --bytes 1000```
2. verify that the file created has 1249 bytes, and should have 1000

**Comment by massahud-fixeads** [comment]
You can generate a random ascii file with the following command
```sh
base64 /dev/urandom | head -c 12558918857 > file.txt
```

**Comment by rlopes-fixeads** [comment]
Thanks it is fixed.
